### ISSUE TITLE
Still got error v0.4.0 from githun

### ISSUE THREAD

**Issue by filoor** [irritanterik/homey-http-request-actions#4]
if i do get
 https://autoremotejoaomgcd.appspot.com/sendmessage?key=APA91bGyxlKdasd3DS5Ssx2gbWPzC8KIaWUznv3tJJ8RT8jRWJ_m3WLFJKy_ZNYRvCAZG_C7bL2V4rnOTSdt8FMkasderELwqrVkQz5msFuVQqZRaC_PGsad3Nz4roLov_lOtVHburCXTil3aa33ff3eWADarkPEkRc20GpNOwSNbOR5RfQKt-jC1TBg&message=SMS%200644542136=:=TEST%20verstuurd&password=123456

still got a error
Changed some values in te link

**Comment by irritanterik** [comment]
Do you have a screenshot of the card? And paste the JSON?

**Comment by filoor** [comment]
And paste the JSON? how you mean dont need a jason just a get http

![1](https://cloud.githubusercontent.com/assets/3647638/13253275/922ea63c-da3b-11e5-9290-01d851830d14.jpg)

**Comment by irritanterik** [comment]
You need to put the request querystring parameters in the JSON field (and
thus use the HTTP Get JSON card). This is necessary because Homey will
escape characters like & from the get URL. Use this JSON:

{

 "key":"APA91bGyxlKdasd3DS5Ssx2gbWPzC8KIaWUznv3tJJ8RT8jRWJ_m3WLFJKy_ZNYRvCAZG_C7bL2V4rnOTSdt8FMkasderELwqrVkQz5msFuVQqZRaC_PGsad3Nz4roLov_lOtVHburCXTil3aa33ff3eWADarkPEkRc20GpNOwSNbOR5RfQKt-jC1TBg",
   "message":"SMS%200644542136=:=TEST%20verstuurd",
   "password":"123456"
}

2016-02-23 14:41 GMT+01:00 filoor notifications@github.com:

**Comment by filoor** [comment]
Gone test it

**Comment by filoor** [comment]
STILL NOTING
![naamloos](https://cloud.githubusercontent.com/assets/3647638/13254962/0d069fa6-da44-11e5-8bb2-1da0761f9fba.png)

**Comment by irritanterik** [comment]
And after removing the trailing ? at the URL?

2016-02-23 15:42 GMT+01:00 filoor notifications@github.com:

**Comment by filoor** [comment]
Sorry also diden't help

**Comment by filoor** [comment]
https://autoremotejoaomgcd.appspot.com/sendmessage?key=APA91bGyxlKOu085Ssx2gbWPzC8KIaWUznv3tJJ8RT8jRWJ_m3WLFJKy_ZNYRvCAZG_C7bL2V4rnOTSdt8FMkxPi30EELwqrVkQz5msFuVQqZRaC_PG5VOKNz4roLov_lOtVHburCXTil3aCr2KWADarkPEkRc20GpNOwSNbOR5RfQKt-jC1TBg&message=SMS%200648146532=:=TEST%20verstuurd&password=123456/
this is the Url
